<table>
  <tr>
    <th>url</th>
    <th>hits</th>
    <th>avg</th>
    <th>max</th>
    <th>min</th>
    <th>var</th>
  </tr>
  <visits>
    <tr>
      <td><method/> <url/></td>
      <td><hits/></td>
      <td><avg/>ms</td>
      <td><max/>ms</td>
      <td><min/>ms</td>
      <td><var/></td>
    </tr>
  </visits>
</table>
